/**
 * Every policy Spiral Slim's Brave Maximum Privacy preset sets, by name.
 *
 * Copied from `apps/slim/Presets/Brave/Maximum Privacy Preset.json` — the file
 * the tool actually reads. Regenerate by reading that file's `Features` keys;
 * do not hand-edit, and do not add a name the preset does not set. The page's
 * whole argument is that these are the real ones.
 */
export const SLIM_POLICIES: string[] = [
  "MetricsReportingEnabled",
  "SafeBrowsingExtendedReportingEnabled",
  "UrlKeyedAnonymizedDataCollectionEnabled",
  "BraveP3AEnabled",
  "BraveStatsPingEnabled",
  "SafeBrowsingProtectionLevel",
  "AutofillAddressEnabled",
  "AutofillCreditCardEnabled",
  "PasswordManagerEnabled",
  "PasswordLeakDetectionEnabled",
  "BrowserSignin",
  "BraveGlobalPrivacyControlEnabled",
  "BraveDeAmpEnabled",
  "BraveDebouncingEnabled",
  "BraveTrackingQueryParametersFilteringEnabled",
  "BraveReduceLanguageEnabled",
  "WebRtcIPHandling",
  "QuicAllowed",
  "NetworkPredictionOptions",
  "BlockThirdPartyCookies",
  "PaymentMethodQueryEnabled",
  "AlternateErrorPagesEnabled",
  "DefaultNotificationsSetting",
  "DefaultGeolocationSetting",
  "DefaultSensorsSetting",
  "BraveRewardsDisabled",
  "BraveWalletDisabled",
  "BraveVPNDisabled",
  "BraveAIChatEnabled",
  "BraveNewsDisabled",
  "BraveTalkDisabled",
  "BravePlaylistEnabled",
  "BraveWebDiscoveryEnabled",
  "BraveSpeedreaderEnabled",
  "TorDisabled",
  "SyncDisabled",
  "EmailAliasesEnabled",
  "DefaultBraveAdblockSetting",
  "DefaultBraveFingerprintingV2Setting",
  "DefaultBraveHttpsUpgradeSetting",
  "DefaultBraveReferrersSetting",
  "DefaultBraveRemember1PStorageSetting",
  "BackgroundModeEnabled",
  "EnableMediaRouter",
  "MediaRecommendationsEnabled",
  "ShoppingListEnabled",
  "AlwaysOpenPdfExternally",
  "TranslateEnabled",
  "SpellcheckEnabled",
  "SearchSuggestEnabled",
  "PrintingEnabled",
  "DefaultBrowserSettingEnabled",
  "DeveloperToolsAvailability",
  "BraveWaybackMachineEnabled",
];
