/** Whop checkout for Spiral Collection ($9.99 one-time).
 *  Generated by scripts/sync-whop.mjs — edit collection/lib/whop.ts instead. */
export const WHOP_CHECKOUT_URL = "https://whop.com/checkout/plan_FYEBP0fCSxw2e";
export const WHOP_PRODUCT_URL = "https://whop.com/spiral-collection/spiral-collection/";
export const WHOP_MANAGE_URL = "https://whop.com/@me/settings/memberships/";
