#!/usr/bin/env node
// Copy Whop URLs from collection/lib/whop.ts into each app's src/lib/whop.ts.
//
//   node scripts/sync-whop.mjs
import { readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = fileURLToPath(new URL("..", import.meta.url));
const CANONICAL = join(ROOT, "collection/lib/whop.ts");

const MIRRORS = [
  "apps/wallpaper/src/lib/whop.ts",
  "apps/clean/src/lib/whop.ts",
  "apps/Resume/src/lib/whop.ts",
  "apps/slim/desktop/src/lib/whop.ts",
];

const canonical = readFileSync(CANONICAL, "utf8");
const keys = ["WHOP_CHECKOUT_URL", "WHOP_PRODUCT_URL", "WHOP_MANAGE_URL"];
const values = {};
for (const key of keys) {
  const m = canonical.match(new RegExp(`export const ${key} = "([^"]+)"`));
  if (!m) {
    console.error(`sync-whop: canonical missing ${key}`);
    process.exit(1);
  }
  values[key] = m[1];
}

const mirrorBody = `/** Whop checkout for Spiral Collection ($9.99 one-time).
 *  Generated by scripts/sync-whop.mjs — edit collection/lib/whop.ts instead. */
export const WHOP_CHECKOUT_URL = "${values.WHOP_CHECKOUT_URL}";
export const WHOP_PRODUCT_URL = "${values.WHOP_PRODUCT_URL}";
export const WHOP_MANAGE_URL = "${values.WHOP_MANAGE_URL}";
`;

for (const rel of MIRRORS) {
  const abs = join(ROOT, rel);
  writeFileSync(abs, mirrorBody);
  console.log(`sync-whop: wrote ${rel}`);
}

console.log("sync-whop: done");
