#!/usr/bin/env node
// Copy Whop URLs from collection/lib/whop.ts into each app's src/lib/whop.ts.
//
//   node scripts/sync-whop.mjs
import { readFileSync, writeFileSync } from "node:fs";
import { join, resolve } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";

const ROOT = fileURLToPath(new URL("..", import.meta.url));
export const CANONICAL = join(ROOT, "collection/lib/whop.ts");

export const MIRRORS = [
  "apps/wallpaper/src/lib/whop.ts",
  "apps/clean/src/lib/whop.ts",
  "apps/Resume/src/lib/whop.ts",
  "apps/slim/desktop/src/lib/whop.ts",
];

export const KEYS = ["WHOP_CHECKOUT_URL", "WHOP_PRODUCT_URL", "WHOP_MANAGE_URL"];

function sync() {
  const canonical = readFileSync(CANONICAL, "utf8");
  const values = {};
  for (const key of KEYS) {
    const m = canonical.match(new RegExp(`export const ${key} = "([^"]+)"`));
    if (!m) {
      console.error(`sync-whop: canonical missing ${key}`);
      process.exit(1);
    }
    values[key] = m[1];
  }

  const mirrorBody = `/** Whop checkout for Spiral Collection ($9.99 one-time).
 *  Generated by scripts/sync-whop.mjs — edit collection/lib/whop.ts instead. */
export const WHOP_CHECKOUT_URL = "${values.WHOP_CHECKOUT_URL}";
export const WHOP_PRODUCT_URL = "${values.WHOP_PRODUCT_URL}";
export const WHOP_MANAGE_URL = "${values.WHOP_MANAGE_URL}";
`;

  for (const rel of MIRRORS) {
    writeFileSync(join(ROOT, rel), mirrorBody);
    console.log(`sync-whop: wrote ${rel}`);
  }

  console.log("sync-whop: done");
}

if (import.meta.url === pathToFileURL(resolve(process.argv[1] ?? "")).href) {
  sync();
}
