// Copy the brand assets this app bundles out of the repo-root /brand folder
// (single source of truth) into gitignored destinations. Same pattern as
// apps/wallpaper/scripts/sync-brand.mjs — never edit a synced copy, it is
// deleted and rewritten on every predev/prebuild.
import { copyFileSync, mkdirSync, rmSync, existsSync } from "node:fs";
import { fileURLToPath } from "node:url";
import path from "node:path";

const here = path.dirname(fileURLToPath(import.meta.url));
const src = path.resolve(here, "../../../../brand");
const marks = path.resolve(here, "../src/assets/brand");

/** [source relative to /brand, filename written into src/assets/brand] */
const MARKS = [
  ["logo/mark-red.svg", "mark-red.svg"],
  ["logo/lockup-red.svg", "lockup-red.svg"],
];

// App icons are NOT synced here. The brand marks are tall and narrow, so
// copying them into src-tauri/icons produced 80x128 and 20x32 files. Icons
// are generated by scripts/make-icon.mjs (`pnpm icon`), which squares the
// mark first and then runs `tauri icon`.

// A standalone checkout of this app has no /brand above it — that folder is a
// monorepo concept. In that case the marks are committed alongside the source
// instead, and syncing is simply not this checkout's job. Treating a missing
// /brand as fatal made the published repository impossible to build, which is
// how this was found: CI cloned it and `pnpm build` failed on the first step.
const alreadyPresent = MARKS.every(([, name]) =>
  existsSync(path.join(marks, name)),
);

if (!existsSync(src) && alreadyPresent) {
  console.log("sync-brand: no /brand above this checkout; using the committed marks");
  process.exit(0);
}

if (!existsSync(src)) {
  console.error(`sync-brand: ${src} not found. /brand must exist at the repo root.`);
  process.exit(1);
}

function sync(dest, files) {
  rmSync(dest, { recursive: true, force: true });
  mkdirSync(dest, { recursive: true });
  for (const [rel, name] of files) {
    const from = path.join(src, rel);
    if (!existsSync(from)) {
      console.error(`sync-brand: /brand/${rel} is missing.`);
      process.exit(1);
    }
    copyFileSync(from, path.join(dest, name));
  }
  return files.length;
}

const copied = sync(marks, MARKS);
console.log(`sync-brand: copied ${copied} marks /brand -> src/assets/brand`);
